<?php

declare(strict_types=1);

namespace Glueful\Extensions\Commerce\Catalog;

use Glueful\Bootstrap\ApplicationContext;

/**
 * Commerce-local seam for a transactional slug reservation authority (design
 * spec §4, Slice-2 Task 1). Commerce NEVER binds an implementation of this
 * interface -- {@see CatalogService} soft-resolves it via a container-has
 * check on every create/rename (mirroring that class's own
 * `EventService`-resolving `dispatch()` idiom), so an unbound install never
 * even attempts to resolve it and create()/rename() stay byte-identical to
 * pre-Task-1 behavior.
 *
 * A bound implementation (e.g. a pack-owned slug ledger) is invoked INSIDE
 * the SAME transaction as the product insert/update it guards -- BEFORE that
 * write -- so any throw from either method rolls back the whole create/
 * rename, including whatever this authority already reserved.
 */
interface SlugLifecycleAuthority
{
    /**
     * Claim the proposed current slug for a brand-new product. $productUuid
     * is pre-generated by the caller (before its own transaction opens) so
     * the authority can reserve the slug against a concrete, already-known
     * product identity. Throws a 422-shaped {@see \Glueful\Validation\ValidationException}
     * on the `slug` field when the slug is reserved by a different product.
     */
    public function prepareCreate(ApplicationContext $c, string $tenant, string $productUuid, string $slug): void;

    /**
     * Claim $new (validate it isn't reserved by a different product) and
     * reserve $old (so the outgoing slug keeps redirecting to this product),
     * in the SAME transaction as the rename's product update. Throws a
     * 422-shaped {@see \Glueful\Validation\ValidationException} on the `slug`
     * field when $new is reserved by a different product.
     */
    public function prepareRename(
        ApplicationContext $c,
        string $tenant,
        string $productUuid,
        string $old,
        string $new
    ): void;
}
